### ISSUE TITLE
State == EntityState.Deleted & SoftDelete don't play nice together. 

### ISSUE THREAD

**Issue by ScarlettCode** [bilal-fazlani/tracker-enabled-dbcontext#101]
If I call the following to delete an address and I have an ISoftDelete interface defined for the address things crash.

```
using (var db = new DataContext())
            {
                var record = db.Addresses.Single(x => x.Id == id); 
                db.Addresses.Attach(record); 
                db.Addresses.Remove(record); 
                db.SaveChanges(auditUserId);
            }
        }
```

Stepping through the code 

https://github.com/bilal-fazlani/tracker-enabled-dbcontext/blob/67ac7ab9d50619a26a9c0ecdacd5324fe4446225/TrackerEnabledDbContext.Common/CoreTracker.cs#L59

is where the crash happens. entry.CurrentValues throws an invalid exception. My assumption is that the softdelete is expecting an EntityState.Modified which would populate the entry.CurrentValues. Something like the below.

```
using (var db = new DataContext())
            {
                var record = db.Addresses
                    .Single(x => x.Id == id);
                record.IsDeleted = true;   
                db.SaveChanges(auditUserId);
            }
        }
```

My original pull request for the soft delete behavior modified a delete that was a soft delete by changing its state from delete to modified and settings the ISoftDelete to true. For my use case this made sense but obviously is probably a little weird. 

What I've done is add an inbetween DataContext in which I do this just so I don't have to go and update all my repo methods. What I want to know is should I look at incorporating this into the tracker and having a settings where it can be turned on or is it not something you see being merged?

Thanks

**Comment by bilal-fazlani** [comment]
I will try to reproduce on local today. Will get back to you on this.

**Comment by txavier** [comment]
Yes, this is definitely a problem.  I am running into this myself.

**Comment by ScarlettCode** [comment]
`public class SoftDeleteDataContext : TrackerContext
{
	private readonly SoftDeleteDataContext _context;

	public SoftDeleteDataContext(string nameOrConnectionString)
		: base(nameOrConnectionString)
	{
		_context = this;
	}

	public virtual int SaveChanges(object userName)
	{
		foreach (DbEntityEntry ent in _context.ChangeTracker.Entries().Where(p => p.State == EntityState.Deleted))
		{
			if (ent.Entity is ISoftDelete)
			{
				ent.State = EntityState.Unchanged;
				var entity = (ISoftDelete)ent.Entity;

				if (entity.IsDeleted == false)
				{
					entity.IsDeleted = true;
				}
				else
				{
					entity.IsDeleted = false;
				}

				ent.State = EntityState.Modified;
			}
		}

		int result = base.SaveChanges();

		return result;
	}

	public override int SaveChanges()
	{
		return SaveChanges(null);
	}
}`

**Comment by bilal-fazlani** [comment]
This has been fixed. Will release nuget soon.
