### ISSUE TITLE
UserName = NULL for ApplicationUsers and ApplicationRoles tables

### ISSUE THREAD

**Issue by dev1909** [bilal-fazlani/tracker-enabled-dbcontext#102]
The most records in the AuditLogs table concerning changes in ApplicationUsers and ApplicationRoles tables have UserName = NULL, although UserContext.UserName != NULL in the Commit method:

public void Commit()
{
     DbContext.Commit(UserContext.UserName);
}

**Comment by bilal-fazlani** [comment]
Commit() ? Where is this method ?
Are you using trackercontext or trackeridentitycontext ?

**Comment by dev1909** [comment]
It's a method in our UnitOfWork class. We're using TrackerIdentityContext, NuGet package version is 3.5.2.

**Comment by bilal-fazlani** [comment]
I can't reproduce on local. Can you show me the code in Commit method ?

**Comment by dev1909** [comment]
Here's the code of our Commit method, which is called in the DbContext.Commit(UserContext.UserName) line:

```
public virtual void Commit(string userName)
        {
            try
            {
                base.SaveChanges(userName);
            }
            catch (DbEntityValidationException e)
            {
                foreach (var eve in e.EntityValidationErrors)
                {
                    Console.WriteLine(@"Entity of type ""{0}"" in state ""{1}"" has the following validation errors:",
                        eve.Entry.Entity.GetType().Name, eve.Entry.State);
                    foreach (var ve in eve.ValidationErrors)
                    {
                        Console.WriteLine(@"- Property: ""{0}"", Error: ""{1}""",
                            ve.PropertyName, ve.ErrorMessage);
                    }
                }
                throw;
            }
        }
```

It's located in our entities class:

```
public class PortalEntities : TrackerIdentityContext<ApplicationUser>
    {
        public PortalEntities() : base("PortalEntities") { }
        ...
    }
```

**Comment by bilal-fazlani** [comment]
Okay,
In your first message you said

The most records in the AuditLogs table concerning changes in
ApplicationUsers and ApplicationRoles tables have UserName = NULL, although
UserContext.UserName != NULL in the Commit method.

What are these most records ?
Do you see a pattern ?

**Comment by dev1909** [comment]
Yes, I've just figured out when exactly is this happening.
If I just get some object from the DB, change its properties and call Commit method, it is saved with the UserName in the AuditLogs table.
But if any methods of Microsoft.AspNet.Identity.UserManager (or Microsoft.AspNet.Identity.RoleManager for Roles) class are called (such as Create, Update, Delete) then the appropriate entry in the AuditLogs table is added withoud UserName.

**Comment by bilal-fazlani** [comment]
Can you confirm if https://www.nuget.org/packages/TrackerEnabledDbContext.Identity/3.5.20-beta solved this issue ?

I have added one method `ConfigureUsername(Func<string>)`

**Comment by bilal-fazlani** [comment]
Just use this code

```c#
public class UsersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private UserManager<ApplicationUser> _userManager;

        public UsersController()
        {
            db.ConfigureUsername(() => User?.Identity?.Name);
            _userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
        }

//you code here
}
```

**Comment by dev1909** [comment]
Hi, I've updated the package version to 3.5.20-beta and tried this code, but I get Exception with the message "Type 'System.Data.Entity.DynamicProxies.ApplicationUser_60D63D21EE7CBB641D6459321290D9AB63344C4B88A782E466501545744FC91F' is not found in context 'AMANA.XBRL.Portal.Data.PortalEntities'" when I perform some of the actions using Microsoft.AspNet.Identity.UserManager.

**Comment by bilal-fazlani** [comment]
Can you try version [3.6.0 ](https://www.nuget.org/packages/TrackerEnabledDbContext/3.6.0)

**Comment by bilal-fazlani** [comment]
Let me know if 3.6 fixes the issue ?

**Comment by dev1909** [comment]
Hi, yes it works with 3.6.0, thank you!
