### ISSUE TITLE
How to track changes to ApplicationUser and ApplicationRole

### ISSUE THREAD

**Issue by hanchoong** [bilal-fazlani/tracker-enabled-dbcontext#104]
I have added reference to the TrackerEnabledDbContext.Identity
and change the ApplicationDbContext as below

```
Public Class ApplicationDbContext
    Inherits TrackerIdentityContext(Of ApplicationUser)
```
And have added the following config
`        GlobalTrackingConfig.DisconnectedContext = True
`

But any changes to user or roles e.g. create new user are not logged to the AuditLog tables.
What else do need to be done to log the changes of users and roles.

Regards.

**Comment by last1here** [comment]
You could use fluent api explained in the wiki [here](https://github.com/bilal-fazlani/tracker-enabled-dbcontext/wiki#fluent-api-configuration). So something along the lines of (c#):

```
EntityTracker
    .TrackAllProperties<ApplicationUser>();
```

**Comment by hanchoong** [comment]
Thanks! 
The changes are logged but as anonymous user. 
How do we log the username too? I know for our own model we need to pass the username to SaveChanges(username).
But in this case there are part of the AspNet.Identity model .

**Comment by bilal-fazlani** [comment]
@hanchoong @last1here 
This will be solve in next release.

So you can do this :

```
            ApplicationDbContext db = new ApplicationDbContext();
            db.ConfigureUsername(() => User.Identity.Name);
```

`.ConfigureUsername()` method accepts a `Func<string>` which acts as a username factory. This func will be called whenever you call `SaveChanges()` or `SaveChangesAsync()` without a username. 

If you configure it as shown above, it should solve your issue. I will update you once I release it.

**Comment by bilal-fazlani** [comment]
Can you confirm if https://www.nuget.org/packages/TrackerEnabledDbContext.Identity/3.5.20-beta solved this issue ?

**Comment by bilal-fazlani** [comment]
Just use this code

```c#
public class UsersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private UserManager<ApplicationUser> _userManager;

        public UsersController()
        {
            db.ConfigureUsername(() => User?.Identity?.Name);
            _userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
        }

//you code here
}
```
