### ISSUE TITLE
Invalid object name 'dbo.AuditLogs1'

### ISSUE THREAD

**Issue by dominusbelial** [bilal-fazlani/tracker-enabled-dbcontext#107]
getting this strange exception while trying to implement your library...

it fires during await db.SaveChangesAsync(HttpContext.Current.User.Identity.Name), log tables are not being populated (but they were created during migration )...

InnerException Message "Invalid object name 'dbo.AuditLogs1'."

this is my ef model definition ... is hosted on a mvc5 application with owin3, i couldn't make it work with TrackerIdentityContext.... 

can you shed some light on this issue?

my model...
public partial class myModel: TrackerContext 
    {
        public myModel()
            : base("name=myModel")
        {
            Configuration.LazyLoadingEnabled = false;
            Configuration.AutoDetectChangesEnabled = false;
            Configuration.ProxyCreationEnabled = false;
        }
.....

post method on webapi controller...
[ResponseType(typeof(Order))]
        [AntiForgeryValidate]
        //[HttpPost]
        public async Task<IHttpActionResult> PostOrder(Order order)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            db.Order.Add(order);
await db.SaveChangesAsync(HttpContext.Current.User.Identity.Name);

{"Message":"An error has occurred.","ExceptionMessage":"An error occurred while updating the entries. See the inner exception for details.","ExceptionType":"System.Data.Entity.Infrastructure.DbUpdateException","StackTrace":"   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at TrackerEnabledDbContext.TrackerContext.<SaveChangesAsync>d__29.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at TrackerEnabledDbContext.TrackerContext.<SaveChangesAsync>d__31.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at QuimpaPHPlus.Controllers.OrdenApiAsyncController.<PostOrden>d__21.MoveNext() in d:\\QUIMPA.ORG\\quimpa\\Mainline\\QuimpaPHPlus\\Controllers\\OrdenApiAsyncController.cs:line 399\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()","InnerException":{"Message":"An error has occurred.","ExceptionMessage":"An error occurred while updating the entries. See the inner exception for details.","ExceptionType":"System.Data.Entity.Core.UpdateException","StackTrace":"   at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.<UpdateAsync>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Data.Entity.Core.Objects.ObjectContext.<ExecuteInTransactionAsync>d__3d`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Data.Entity.Core.Objects.ObjectContext.<SaveChangesToStoreAsync>d__39.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.<ExecuteAsyncImplementation>d__9`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Data.Entity.Core.Objects.ObjectContext.<SaveChangesInternalAsync>d__31.MoveNext()","InnerException":{"Message":"An error has occurred.","ExceptionMessage":"Invalid object name 'dbo.AuditLogs1'.","ExceptionType":"System.Data.SqlClient.SqlException","StackTrace":"   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__167_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.Execute()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.<ExecuteAsync>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.<UpdateAsync>d__0.MoveNext()"}}}

**Comment by bilal-fazlani** [comment]
Code first ? Model first? Database first ?

**Comment by dominusbelial** [comment]
Code first

**Comment by bilal-fazlani** [comment]
which version of nuget package ?

**Comment by dominusbelial** [comment]
3.6.0 ? Just updated yesterday

**Comment by dominusbelial** [comment]
just noticed this on sql profiler..., why is EF doing this? i already cleaned up temporary files and stuff..

exec sp_executesql N'INSERT [dbo].[AuditLogs1]([UserName], [EventDateUTC], [EventType], [TypeFullName], [RecordId])
VALUES (@0, @1, @2, @3, @4)
SELECT [AuditLogId]
FROM [dbo].[AuditLogs1]
WHERE @@ROWCOUNT > 0 AND [AuditLogId] = scope_identity()',N'@0 nvarchar(max) ,@1 datetime2(7),@2 int,@3 nvarchar(512),@4 nvarchar(256)',@0=N'gpoveda',@1='2016-05-23 22:03:50.5972327',@2=0,@3=N'QuimpaPHPlus.Models.Orden',@4=N'8348'

**Comment by dominusbelial** [comment]
got it, i removed the following lines from the model, now is adding rows to the log and details, that was tricky one!

public virtual DbSet<AuditLogDetails> AuditLogDetails { get; set; }
public virtual DbSet<AuditLogs> AuditLogs { get; set; }

**Comment by bilal-fazlani** [comment]
To narrow down the issue,
Can u first try removing

```c#
Configuration.LazyLoadingEnabled = false;
Configuration.AutoDetectChangesEnabled = false;
Configuration.ProxyCreationEnabled = false;
```

If it still fails, try using version 3.5.2

Let me know

**Comment by bilal-fazlani** [comment]
How did u add the decorator to the poco classes? You shouldn't be able to modify auditlog and auditlogdetails class. They are a lart of this library

**Comment by dominusbelial** [comment]
[Table("AuditLogs")]
    public partial class AuditLogs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AuditLogs()
        {
            AuditLogDetails = new HashSet<AuditLogDetails>();
        }

        [Key]
        public long AuditLogId { get; set; }.....

**Comment by bilal-fazlani** [comment]
Something is wrong. Looks like you have created your own auditlogs class when it already exist in tedb library. That's why you got that error of "auditlogs1".

You need to remove the auditlogs and auditlogdetails classes that you have created.

**Comment by dominusbelial** [comment]
i just removed both of them and logging still works so these are not needed, i regenerated the model becouse i had other pending changes and the new pocos were included by mistake

**Comment by bilal-fazlani** [comment]
Yeah you are right. Well now that you have created an issue, people might google for this exception and find this solution.
