### ISSUE TITLE
Possibility to extend Audit Log Record to include extra data such as User IP address?

### ISSUE THREAD

**Issue by Korayem** [bilal-fazlani/tracker-enabled-dbcontext#109]
Is it possible to extend `TrackerEnabledDbContext` entities by adding more properties and fill them up using `OnAuditLogGenerated` event?

**Comment by bilal-fazlani** [comment]
You can save these extra properties in a separate table in the event with a foreign key of generated log.
I Hope that helps

**Comment by Korayem** [comment]
Makes perfect sense. Sometimes the most obvious thing is quite blurred :)

I already implement [Events](https://github.com/bilal-fazlani/tracker-enabled-dbcontext/wiki/5.-Events) in my code to update several fields to log both DateTime and Actor of `Creation`, `LastUpdated`, `Deleted` and `Undeleted` by adding my event `OnAuditLogGenerated`.

**Comment by Korayem** [comment]
But how would I pass the IP into `OnAuditLogGenerated`?

**Comment by bilal-fazlani** [comment]
https://github.com/bilal-fazlani/tracker-enabled-dbcontext/wiki/7.-Metadata
will release soon

**Comment by Korayem** [comment]
Sweetness!
