### ISSUE TITLE
Virtual DbSets and methods GetLogs

### ISSUE THREAD

**Issue by ChewieWookie** [bilal-fazlani/tracker-enabled-dbcontext#113]
Could you make DbSets of AuditLog and AuditLogDetails virtual?
And maybe also GetLogs methods? 

It is very helpful when unit testing with mock frameworks like Moq

**Comment by bilal-fazlani** [comment]
Good point

**Comment by ChewieWookie** [comment]
Hmm I also have one suggestion to tracking changes of relations. 
Foreign Key tracking is ok but I wonder if you can add to tracking foreign keys at least the full name of Type related object? 

I had to make one hell of reflection mechanism to compose user readable messages for relation changes.

As i see it if simple primitive property is tracked such field would be null and in case of relations we have key + full name of object, so based on those two columns it is simple to extinguish one from antoher

**Comment by bilal-fazlani** [comment]
@ChewieWookie  
>so based on those two columns it is simple to extinguish one from another
What do you want to extinguish ? What value will it add to every user of this library ?

**Comment by ChewieWookie** [comment]
Easier retrieval of relation objects properties.

Lets Assume we have Entity with two relation objects.

`int Id_ObjA;
ObjA ObjA

int Id_ObjB
ObjB ObjB

public class ObjA{
    int Id;
    string NameA;
} 
public class ObjB{
    int Id;
    string NameB;
} 
`

We want to compose history for user but we don't want to show message like 'ObjA changed from Id 1 to 2' but 'ObjA changed from Hello to Hi'

But we cannot distinguish between ObjA and B. All we have in AuditLogDetails is PropertyName: Id_ObjA, OriginalValue: 1, NewValue: 2.

I used a reflection mechanism to find the type of such relation object by spliiting property name Id_ObjA by undersore sign and then used second item as type name, search assembly for such type, pass type with id to generic method that returned proper object (but not casted, plain object so still do not have any info about properties inside at compilation time) and then try to retirieve value of the property I wanted (In fact created interface with one method returning string, implemented it on all entites to have one point to retrieve such historic user friendly description of givn entity).

And that is quite complex and for newcomer to project hard to understand. And also easily breakable (Just change Foreig key from Id_ObjA to ObjAId and you have to modify splitting the name of property from LogDetails) 

But with full name of relations Objects Type this procedure can be much easier and more reliable as you don't have to rely on splitting a property name that can be changed by mistake. 

However if you intend to somehow support relations in more advanced way (for example track Id's but during retrievieng from Db put there actual object like EF is doing with relations) then I guess you can completly ignore this suggestion ;)

**Comment by bilal-fazlani** [comment]
Alright let's create another github issue for this and tackle it separately. I will close this issue after making everything virtual.
