### ISSUE TITLE
Create AuditLogDetails Entries for Unchanged Properties

### ISSUE THREAD

**Issue by ojraqueno** [bilal-fazlani/tracker-enabled-dbcontext#120]
When updating, is it possible to create AuditLogDetails entries for all properties, including those that are unchanged?

What I ultimately want to achieve is to get a snapshot of an entity at a certain point in time, i.e. just before an update.

**Comment by bilal-fazlani** [comment]
As of now, It's not possible. 
But, If you have all the data, can you not build a snapshot of a particular date based on history ?

**Comment by ojraqueno** [comment]
Thanks for the confirmation.

Yes, that's the same suggestion I made to the comment that prompted my opening of this issue: http://www.ojdevelops.com/2016/06/auditing-changes-with-entity-framework.html

Kind regards.

**Comment by bilal-fazlani** [comment]
Nice work writing the blog article!
