### ISSUE TITLE
Separated Database for Auditing 

### ISSUE THREAD

**Issue by SMRockend** [bilal-fazlani/tracker-enabled-dbcontext#125]
I have scenario which i need to store all audit tables in separate database. 

Just wondering if i can do that in current library or perhaps pass two different context ?

Cheers,
Amir

**Comment by bilal-fazlani** [comment]
Hi,
Take a look at
https://github.com/bilal-fazlani/tracker-enabled-dbcontext/wiki/5.-Events

**Comment by SMRockend** [comment]
Thanks mate.
