### ISSUE TITLE
Time zone conversion

### ISSUE THREAD

**Issue by jwils-uofdn** [bilal-fazlani/tracker-enabled-dbcontext#126]
Great tool.  Would like to suggest the ability to convert to a specific time zone when storing AuditLog data.

**Comment by flux88** [comment]
Hi, it stores the time in UTC. So can you not just convert it to your desired timezone upon retrieval (DateTime.ToLocalTime)?

**Comment by jwils-uofdn** [comment]
Certainly can.  Thought it might be useful to be able to set once but not a high priority.
