### ISSUE TITLE
Update Perfomance

### ISSUE THREAD

**Issue by garypoker3** [bilal-fazlani/tracker-enabled-dbcontext#134]
Hi,
Love this library but I  run into some perfomance issue with big amount of entities  when update took 3  times longer ..

In  SqlProfiler i noticed  that before every update it does number of  select queries equals to number of 

entity fields , is that by design  how it compares original and new , or i'm doing something wrong? 

 i am attaching entities manually  - _dbContext.Blogs.Attach(blog);  ..

and config is  - GlobalTrackingConfig.DisconnectedContext = true;

thanks

**Comment by bilal-fazlani** [comment]
This is the cost you have to pay when you are attaching entities manually AND using this library. 
You see, the responsibility of this library is to store previous and new value of en entity on an update operation. When you attach an entity manually, the built-in tracker of EF doesn't know about it's previous state. And hence this library has to go to database and fetch all values.

The only other solution to reduce number of calls and still use this library is, don't attach entities manually. If you do this, the number of calls will be 1 update call + 1 get call (compared to previous, 1 update call + n select calls where n being number of fields in the entity)
