### ISSUE TITLE
How to track audit of user logins and locations

### ISSUE THREAD

**Issue by weedkiller** [bilal-fazlani/tracker-enabled-dbcontext#142]
Hi, this is a nice nuget addition, I would like to suggest a global options where we can enable - track globals items like below.

DateTime
UserName
Location - latLon
HostName (Ip from where)
Browser
[
Heres a link for further ref](http://rion.io/2013/03/03/implementing-audit-trails-using-asp-net-mvc-actionfilters/)

Thanks

**Comment by bilal-fazlani** [comment]
Its possible with [metadata](https://github.com/bilal-fazlani/tracker-enabled-dbcontext/wiki/7.-Metadata)
