### ISSUE TITLE
Sign TrackerEnabledDbContext?

### ISSUE THREAD

**Issue by melucas** [bilal-fazlani/tracker-enabled-dbcontext#15]
You have signed the other two assemblies, could you also sign TrackerEnabledDbContext?

**Comment by melucas** [comment]
Error  Assembly generation failed -- Referenced assembly 'TrackerEnabledDbContext' does not have a strong name

**Comment by bilal-fazlani** [comment]
Ok. Will do.
Thank you for informing

**Comment by melucas** [comment]
Thanks!
