### ISSUE TITLE
Entry as Modified not traking the changes. 

### ISSUE THREAD

**Issue by danielmeza** [bilal-fazlani/tracker-enabled-dbcontext#150]
I have the following code on my Repository patther,
 ```
        public void EntryAsModify<T>(T entity) where T : class
        {
            DbEntityEntry<T> contextEntry = Context.Entry(entity);
            contextEntry.State = EntityState.Modified;
        }
```
and I im using like this:

```
                repository.EntryAsModify(page);
                foreach (var casenumber in page.CaseNumbers)
                {
                    repository.EntryAsModify(casenumber);
                }
                page.AssingUserID = null;
                page.NotificationState &= ~NotificationState.Audit;
                page.NotificationState |= NotificationStateValidator.GetNotificationState(audit.AuditState);
                repository.EntryAsModify(page.Document);
                repository.Update(page);
                scope.Complete();
```
But only in the page are tracking the changes, all 3 entities, Document, Page and CaseNumber has the TrackChanges attribute, one document can have many pages, one page should have a document, a page can have many CaseNumbers and one CaseNumber should have one page.

I see the only changes tracking are in the NotificationState and the AssingUserID because are made before to use the EntiryAsModify method, the entity CaseNumber is edited outside of this method and the changes are allready maded on this time.

**Comment by andy952** [comment]
I was having this issue yesterday. Have you tried setting            
`GlobalTrackingConfig.DisconnectedContext = true;` on your DbContext?

**Comment by bvansteelandt** [comment]
Setting ```GlobalTrackingConfig.DisconnectedContext = true;``` does indeed fix this issue. This can be closed. @bilal-fazlani

**Comment by bilal-fazlani** [comment]
Ok closing this. Thanks for the update.
