### ISSUE TITLE
Using of deprecated dependency EntityFramework.MappingAPI

### ISSUE THREAD

**Issue by richieeeeeeee** [bilal-fazlani/tracker-enabled-dbcontext#155]
Hi,
trackerendabledbcontext.common requires EntityFramework.MappingAPI, which is deprecated: 
https://www.nuget.org/packages/EntityFramework.MappingAPI/
Is it possible to remove/replace this dependency?
Thanks!

**Comment by tedbcsgpro** [comment]
Saw that mappingAPI was removed 15 days ago. Lookup forward to an updated NuGet package without this dependency. Thank you.

**Comment by bilal-fazlani** [comment]
Yes, I will do this tonight

**Comment by vmtco** [comment]
I'm waiting for you

**Comment by furier** [comment]
me2

**Comment by minoseah629** [comment]
thank you.

**Comment by furier** [comment]
still waiting...

**Comment by jannohordijk** [comment]
Please solve this. I just tried your package and got the same error (Dutch):

 "Kan bestand of assembly EntityFramework.MappingAPI, Version=6.1.0.9, Culture=neutral, PublicKeyToken=7ee2e825d201459e of een van de afhankelijkheden hiervan niet laden. De manifestdefinitie van de gevonden assembly komt niet overeen met de assembly-verwijzing. (Uitzondering van HRESULT: 0x80131040)" | string

**Comment by vmtco** [comment]
Use this command in Package Manager Console to solve error `Update-Package EntityFramework.MappingAPI -Version 6.1.0.9` until resolve it

**Comment by jannohordijk** [comment]
Thank you, that did the trick. Best regards!

**Comment by merccat** [comment]
Thank you for the work around as well and thanks for a great package!  Looking forwarded to an updated version without the dependency.

**Comment by traelthompson75** [comment]
I tried your suggested fix with the NuGet command Update-Package EntityFramework.MappingAPI -Version 6.1.0.9 and I am still getting the error....  Any help would be greatly appreciated.

**Comment by furier** [comment]
make sure the version is actually changed, sometimes if you have other
dependencies which depend on the newer version it will upgrade it for you
when downgrading which is kind of annoying as you would think you
downgraded it but you didn't... also manually clear out packages and global
packages cache, bin/obj folders etc and try again.

tor. 14. jun. 2018 kl. 19:01 skrev Trae Thompson <notifications@github.com>:

**Comment by traelthompson75** [comment]
Thanks for your suggestion.
I tried deleting everything from all bin/debug and the packages folder in the solution and still no dice. I am so stumped....

**Comment by traelthompson75** [comment]
Ok. Thank you so much! After going through every folder. And deleting out that worked!!!

**Comment by furier** [comment]
you are welcome :)

tor. 14. jun. 2018 kl. 20:22 skrev Trae Thompson <notifications@github.com>:

**Comment by asulwer** [comment]
I have already removed this from my branch.

**Comment by furier** [comment]
have you created a PR for this then?

ons. 18. jul. 2018 kl. 22:39 skrev Aaron Sulwer <notifications@github.com>:

**Comment by bilal-fazlani** [comment]
I think there is a PR. https://github.com/bilal-fazlani/tracker-enabled-dbcontext/pull/158

@asulwer let's resolve the conflicts first. would you be able to do that or will need any permissions on the repo?

**Comment by asulwer** [comment]
@bilal-fazlani I removed all of those conflicts in a previous PR that has been merged into the main branch.  Version number wasn't changed.

PR#158 is a huge change to support Core 2.0 (untested with 2.1).  The entire solution was restructured.  I am missing test for Core.  I started a web project to test some features.  The current committed fork is up to date, as of yesterday

I wouldn't mind having my privileges being elevated so I can merge this PR into the main branch.

**Comment by furier** [comment]
Could also just publish the core version as prerelease to nuget if not yet
satisfied.

Den tor. 19. jul. 2018, 18.17 skrev Aaron Sulwer <notifications@github.com>:

**Comment by bilal-fazlani** [comment]
Yeah, I am thinking, two parallel packages make sense. The non-core version of this package still might continue to evolve with non-core version of EF.

Let's maintain a branch for core version and continue to deploy the core version of nuget from that branch.

the current non-core package runs tests on every commit but does not have a automated deployment provision. I have been doing that manually so far and have not been able to do one since I don't have a windows machine anymore. Anyways, with the core version, let's setup a different pipeline to build, test and deploy on appveyor. 

I can share my nuget key with you so we can share the deployment ownership. thoughts?

**Comment by asulwer** [comment]
I have already deployed the Core version to nuget.  I please let me know if I did this incorrectly.

**Comment by minoseah629** [comment]
TrackerEnabledDbContext has a Dependency to its common nuget package.  

Common still has the dependency of EntityFramework.MappingAPI 6.1.0.9

![image](https://user-images.githubusercontent.com/1980068/43789025-ed49b872-9a3c-11e8-9566-041ae2a17afe.png)

**Comment by alex-milburn** [comment]
Same issue as minoseah629

**Comment by guillaumejay** [comment]
I solved by downloading the current code source and reference it directly, but I'd rather have a updated nuget package.

**Comment by asulwer** [comment]
I do not think that the nuget package has been updated.  The Core version that I created does have it removed and IS a nuget package

**Comment by StevenNell** [comment]
Is there any resolution to this yet?

**Comment by StevenNell** [comment]
@asulwer @bilal-fazlani I see that the dependency has been removed in the project - could you please update the nuget package?

**Comment by StevenNell** [comment]
@guillaumejay Would you care to share exactly how you did that, please?

**Comment by asulwer** [comment]
@StevenNell use nuget to get the latest that supports Core 2+

**Comment by minoseah629** [comment]
@bilal-fazlani, any update to generate the nuget package?

**Comment by ChocoMachine** [comment]
> Use this command in Package Manager Console to solve error Update-Package EntityFramework.MappingAPI -Version 6.1.0.9 until resolve it...

The above no longer works as EntityFramework.MappingAPI -Version 6.1.0.9 has been removed! 

Could you update the nuget package as your library is not usable in it's current package.

**Comment by JardarM** [comment]
We would be greatfull if the nuget package could be updated.

**Comment by jwindhor** [comment]
Dear Team, 
We really love your solution and have it incorporated in all our enterprise solutions!

However, as you know it has now reached a critical point where the existing package and its dependencies are no longer functional. 

Do you have any ETA on this updated package? Please advise ASAP so we can determine a path forward and ensure no business interruptions. 

Thanks in advance.

**Comment by bilal-fazlani** [comment]
This should be resolved now thanks to @Askolein
