### ISSUE TITLE
Could not load file or assembly 'EntityFramework.MappingAPI, Version=6.1.0.9, Culture=neutral, PublicKeyToken=7ee2e825d201459e' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

### ISSUE THREAD

**Issue by ChocoMachine** [bilal-fazlani/tracker-enabled-dbcontext#161]
Can't get this working, not even with the pre-release.  it just dosn't like this EntityFramework.MappingAPI..

**Comment by muradkarakas** [comment]
solved.

Solution is to download whole solution. Unzip it. Then add 2 C# projects into your solution. (TrackerEnabledDbContext and TrackerEnabledDbContext.Common) then compile. It works for me.

**Comment by minoseah629** [comment]
#155 is the exact same issue and still have yet to be resolved.

**Comment by bilal-fazlani** [comment]
This should be resolved now thanks to @Askolein
