### ISSUE TITLE
Multiple SELECT queries with GlobalTrackingConfig.DisconnectedContext = true

### ISSUE THREAD

**Issue by ahahcbigeim** [bilal-fazlani/tracker-enabled-dbcontext#162]
https://github.com/bilal-fazlani/tracker-enabled-dbcontext/blob/b3fd3d922f4612e9abb90b78ed71847cfff4ffa9/TrackerEnabledDbContext.Common/Auditors/ChangeLogDetailsAuditor.cs#L88

It'll be nice to call GetDatabaseValues() only once, and cache the result. That way comparing N properties of a changed entry wouldn't result in N SELECT queries.

**Comment by bilal-fazlani** [comment]
@ahahcbigeim , If you think it's feasible, could you please submit a PR?

**Comment by bilal-fazlani** [comment]
Thanks. You now have collaborator rights on this repo so you will be able to merge pull requests. Just make sure you write test and those tests pass.
