### ISSUE TITLE
Nuget package

### ISSUE THREAD

**Issue by pablotdv** [bilal-fazlani/tracker-enabled-dbcontext#167]
Is the Nuget Packages update to date?

The Issue #162 has happened in my project and @ahahcbigeim already approved related PR.

So, What I need to do for this issue about multiples queries execution when I have `GlobalTrackingConfig.DisconnectedContext = true;`?

**Comment by bilal-fazlani** [comment]
Hi, @pablotdv ,
Unfortunately there is no automation to deploy these nuget packages. And I don’t  have a windows machine to manually deploy it right now. Would you be interested in building a travis ci pipeline which builds and deploys?

**Comment by pablotdv** [comment]
Hi @bilal-fazlani 

I can try to help you.
Do you already have a pipeline at Travis-CI?
Can you give me access?

**Comment by bilal-fazlani** [comment]
There is an appveyor pipeline here: https://ci.appveyor.com/project/bilal-fazlani/tracker-enabled-dbcontext

It builds and runs all tests on every commit. May be it will be easier to extend this pipeline to do the deployments too.

**Comment by bilal-fazlani** [comment]
We want the deployments to happen when there is a git `tag` present.  This repo contains multiple C# projects so we can take the approach we have taken here : https://github.com/bilal-fazlani/commanddotnet 

In commanddotnet, we tag projects with syntax: `PROJECTNAME_VERSION` and then deploy specific projects with given version.

**Comment by bilal-fazlani** [comment]
I can give you maintainer access to this repo so you can get started on appveyor. While playing around with appveyor, ideally we dont want to create too many fake tags. Can you think of an approach where we can test the pipelines without creating a lot of tags?

**Comment by bilal-fazlani** [comment]
hmmm.. After merging the PR, I am facing issues trying to release the Nuget version.

for some reason, we get this error:
```
Deploying using NuGet provider
Publishing TrackerEnabledDbContext.3.8.0.nupkg to https://www.nuget.org/api/v2/package...
Error publishing package. NuGet server returned 403: The specified API key is invalid, has expired, or does not have permission to access the specified package.
```
https://ci.appveyor.com/project/bilal-fazlani/tracker-enabled-dbcontext

I will continue to debug this.

**Comment by bilal-fazlani** [comment]
A new version is release on nuget https://www.nuget.org/packages/TrackerEnabledDbContext/3.8.3

I was adding the key in a wrong way. It works now. Thanks for the PR !

**Comment by azsdaja** [comment]
Hi @bilal-fazlani,
Just spent and hour investigating my issues with this package.
Seems like 3.8.3 version on NuGet still contains DLL with 3.7.0 version! Or at least the DLL properties say so.

**Comment by bilal-fazlani** [comment]
Hi @azsdaja 
I think this may have been the cause for that.

![image](https://user-images.githubusercontent.com/3396271/78333573-b0895580-75a7-11ea-898e-b1154dda4c66.png)

The CI is not perfect at the moment. I will try to fix this as soon as possible. I am curious what issue was it causing?

**Comment by bilal-fazlani** [comment]
PS: If you are interested in helping me fix this, it would be great . and that would be faster

**Comment by azsdaja** [comment]
Sorry, I'd like to help, but I'm not experienced with automatic package creation.
As for my issue — can't remember precisely, I should have started responding to you a few days ago :) — it was about nuget.exe or MSBuild looking for 3.7 DLL version (like in DLL) and not being able to find it (which is weird because the DLL marked with this version was present in 3.8.3 package I installed). And I was assuming there are some leftovers of 3.7 package (in IDE cache or something) and that's why it took me a while to investigate it. 
But on this day I had weird issues with Nuget (for example an error about missing nuspec file when trying to install 3.7 again), so maybe it was my specific case.
