### ISSUE TITLE
Target .netstandard2.1, netcoreapp3.1, and entity framework 6.3/6.4

### ISSUE THREAD

**Issue by chriscamac** [bilal-fazlani/tracker-enabled-dbcontext#168]
My organization https://github.com/milestechnologies is planning to do this work so that we can continue to use this package while we move to support .Net Core 3.1

We plan to submit a pull request for this if you would like to support it.  If not, we can provide to you the fork and perhaps you can offer it to your user base as an alternative.

**Comment by bilal-fazlani** [comment]
I am open to PRs. I can also add you as a maintainer on this repo the codebase is maintained. Let me know.

**Comment by pablotdv** [comment]
How can I use on .net 5 project?

I get this error when I install de package on .net 5 project

```
Severity	Code	Description	Project	File	Line	Suppression State	Tool
Warning	NU1701	Package 'TrackerEnabledDbContext 3.8.3' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0'. This package may not be fully compatible with your project.	
```
