### ISSUE TITLE
No tracking done 

### ISSUE THREAD

**Issue by Avdam** [bilal-fazlani/tracker-enabled-dbcontext#185]
I have a TrackerContext on which Set/Attach for a certain table is called:

        public static void AttachAllModifiedRecords<T>(
            this TrackerContext context,
            IEnumerable<T> records)
            where T : class
        {
            foreach (var record in records)
            {
                var set = context.Set<T>();
                set.Attach(record);
                DbEntityEntry entry = context.Entry(record);
                entry.State = EntityState.Modified;
            }
        }

Now, that table is not audit trailed. Is there a solution?

**Comment by DoubleDot** [comment]
It's in the documentation: https://tracker-enabled-dbcontext.bilal-fazlani.com/techniques/
"
In this pattern, TEDB wont work by default. You will have to set
`GlobalTrackingConfig.DisconnectedContext = true;`
on application startup.
"
