### ISSUE TITLE
Key problem with fluent configuration.

### ISSUE THREAD

**Issue by ghost** [bilal-fazlani/tracker-enabled-dbcontext#20]
I like to use fluent configuration on my repositories and I just realised that I have to mark the key property with [Key] attribute, looks like the tracker engine can't find the key without it. =/
Also, it will be nice if we can mark a model class with TrackChanges without using attributes, I kinda like to keep my model as clean as possible. Maybe a fluent configuration or something alike.

**Comment by bilal-fazlani** [comment]
@paulodotjunior 

> I have to mark the key property with [Key] attribute,

Not necessary anymore (in version 2.7)

> Also, it will be nice if we can mark a model class with TrackChanges without using attributes.

This should be possible. I'll implement this in version 2.8.

**Comment by bilal-fazlani** [comment]
Btw, version 2.7 is not on nuget yet, I will put it there soon.

**Comment by paulodotjunior** [comment]
Nice!
I'll wait for the nuget package and avoid mess with the references of the project.
Thank you for the help!
Great work!

**Comment by bilal-fazlani** [comment]
[version 2.7] (https://www.nuget.org/packages/TrackerEnabledDbContext)  is on nuget

**Comment by paulodotjunior** [comment]
Great, thanks!

**Comment by fluentthinker** [comment]
When downloading this NuGet package, the version of the assembly still seems to be 2.5. Is this correct?

**Comment by bilal-fazlani** [comment]
Yeah. Forgot to change assembly version. But that shouldn't be a problem. 

Nyways' i have logged a defect for it #25

**Comment by bilal-fazlani** [comment]
release 3.0-beta is on nuget. closing issue
