### ISSUE TITLE
Ability to save the audit data to other database ?

### ISSUE THREAD

**Issue by bilal-fazlani** [bilal-fazlani/tracker-enabled-dbcontext#26]

**Comment by Cvijo** [comment]
why you removed this option ? .. having audit logs in another database (not production) have many advantages (different backup plan, slower server ... )

**Comment by bilal-fazlani** [comment]
this option was not implemented. i planned to implement this in version 3.0 but never got time.
the question is still open and will mostly be addressed in a future version.

**Comment by bilal-fazlani** [comment]
An event has been provided where log is given as event argument and can be used to save at a different location. using the same event argument you can skip saving the log to local database if you are saving it to a remote database. I will soon put a documentation on wiki.

**Comment by bilal-fazlani** [comment]
version 3.5 is out on nuget : https://www.nuget.org/packages/TrackerEnabledDbContext/3.5.0
documentation : https://github.com/bilal-fazlani/tracker-enabled-dbcontext/wiki/Events

closing the question
