### ISSUE TITLE
TrackerIdentityContext and IdentityDbContext<ApplicationUser>

### ISSUE THREAD

**Issue by Bunkerbuster** [bilal-fazlani/tracker-enabled-dbcontext#30]
Hi bilal-fazlani,

How do i configure "Step 2: Inherit" if i am using the mvc 5 entity framework and the identity framework > 2.0.0?

I using something like this, as you can see i already inherent from IdentityDbContext

file identityModels.cs

    using Microsoft.AspNet.Identity;
    using Microsoft.AspNet.Identity.EntityFramework;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity;
    using System.Security.Claims;
    using System.Threading.Tasks;
    using TrackerEnabledDbContext.Identity; // --> nuget package is installed

    namespace MyApplication.Models
    {
        public class ApplicationDbContext : IdentityDbContext<ApplicationUser>
       {
           public ApplicationDbContext()
              : base("DefaultConnection", throwIfV1Schema: false)
           {
           }
        
            protected override void OnModelCreating(System.Data.Entity.DbModelBuilder modelBuilder)
            {
                base.OnModelCreating(modelBuilder);
                modelBuilder.Entity<ApplicationUser>()
                    .ToTable("Users", "dbo").Property(p => p.Id).HasColumnName("Id");
                modelBuilder.Entity<IdentityUserRole>()
                    .ToTable("UserRoles");
                modelBuilder.Entity<IdentityUserLogin>()
                    .ToTable("SystemLogins");
                modelBuilder.Entity<IdentityUserClaim>()
                   .ToTable("UserClaims");
                modelBuilder.Entity<IdentityRole>()
                   .ToTable("Roles").Property(p => p.Id).HasColumnName("Id");
                modelBuilder.Entity<ApplicationRole>()
                    .ToTable("Roles").Property(p => p.Id).HasColumnName("Id");
            }

            static ApplicationDbContext()
            { 
            }

            public static ApplicationDbContext Create()
            {
                return new ApplicationDbContext();
            }
        }
    }

**Comment by bilal-fazlani** [comment]
Install package trackerenableddbcontext.identity then
Inherit from trackeridentitycontext<applicationuser>

**Comment by bilal-fazlani** [comment]
like this:

using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Security.Claims;
using System.Threading.Tasks;
using TrackerEnabledDbContext.Identity; // --> nuget package is installed

namespace MyApplication.Models
{
    public class ApplicationDbContext : TrackerIdentityContext<ApplicationUser>
   {
       public ApplicationDbContext()
          : base("DefaultConnection", throwIfV1Schema: false)
       {
       }

        protected override void OnModelCreating(System.Data.Entity.DbModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            modelBuilder.Entity<ApplicationUser>()
                .ToTable("Users", "dbo").Property(p => p.Id).HasColumnName("Id");
            modelBuilder.Entity<IdentityUserRole>()
                .ToTable("UserRoles");
            modelBuilder.Entity<IdentityUserLogin>()
                .ToTable("SystemLogins");
            modelBuilder.Entity<IdentityUserClaim>()
               .ToTable("UserClaims");
            modelBuilder.Entity<IdentityRole>()
               .ToTable("Roles").Property(p => p.Id).HasColumnName("Id");
            modelBuilder.Entity<ApplicationRole>()
                .ToTable("Roles").Property(p => p.Id).HasColumnName("Id");
        }

        static ApplicationDbContext()
        { 
        }

        public static ApplicationDbContext Create()
        {
            return new ApplicationDbContext();
        }
    }
}

**Comment by Bunkerbuster** [comment]
Hi bilal-fazlani,

I needed to restart VS2015 ctp6  and the solution 2 before all the errors where gone. But know it works thanks for your help. It is working.

Looking forward to use this functionality.
