### ISSUE TITLE
Creation of AuditLogDetail Causes Execution of Multiple Database Queries

### ISSUE THREAD

**Issue by Merlin-Taylor** [bilal-fazlani/tracker-enabled-dbcontext#32]
The following call stack is traced for each property of each modified or deleted entity.

* LogDetailsAuditor.OriginalValue
* DbEntryExtensions.GetDatabaseValue
* DbEntityEntry.GetDatabaseValues

This last method causes Entity Framework to execute a database query. This slows down commits which include a number of deleted/modified rows.

**Comment by bilal-fazlani** [comment]
Hi I have added you as a collaborator on this repo. Could you please merge your changes ?
Thanks

**Comment by Merlin-Taylor** [comment]
Hi Bilal,

Thanks for getting back to me so quickly. I've merged that in just now.

Regards,
Merlin
