### ISSUE TITLE
Resolving EventType conflict

### ISSUE THREAD

**Issue by ScarlettCode** [bilal-fazlani/tracker-enabled-dbcontext#34]
Our current project has a model called EventType. I know you can use the Fluent API to map table names and column names but I can't seem to get it right with EventType because its an enum and not an entity? Is there a way to get entity framework to differentiate between the two?

"The type 'TrackerEnabledDbContext.Common.Models.EventType' and the type 'MyProject.Common.Models.EventType' both have the same simple name of 'EventType' and so cannot be used in the same model. All types in a given model must have unique simple names. Use 'NotMappedAttribute' or call Ignore in the Code First fluent API to explicitly exclude a property or type from the model."

I would prefer not to have to change mine and migrate data but if that's the only solution I can do that.

Thanks for you excellent work!

**Comment by bilal-fazlani** [comment]
Are you using the code first approach or model first ?

In either case, can you show me how your model looks like ?

**Comment by bilal-fazlani** [comment]
I was able to reproduce this and tried a couple of things to fix this. Eventually I found out that there is nothing we can do about it except for changing the name of one of the classes/enum. This is one of the limitation of EF as of now. 

References:
http://stackoverflow.com/a/22466391/1365053
http://blog.oneunicorn.com/2013/03/11/ef6-nested-types-and-more-for-code-first/

**Comment by ScarlettCode** [comment]
Are you going to make changes at the source to make the EventType name more unique or should I just make changes my side to work around it?

Thanks for looking into it

**Comment by bilal-fazlani** [comment]
No, I don't think it's a good idea to change the name in source as it will break many other people's code.
Please make changes in your code. 
Besides, this limitation is supposed to go away in future versions of EF.
