### ISSUE TITLE
NuGet Release

### ISSUE THREAD

**Issue by Bestadd** [bilal-fazlani/tracker-enabled-dbcontext#36]
http://bilal-fazlani.blogspot.in/2013/09/adding-log-audit-feature-to-entity.html references a 5 March 2015 release but the last time NuGet was update was 26 March 2015.  Would it be possible to have the NuGet package updated with the latest release build?

**Comment by bilal-fazlani** [comment]
hi
what ever http://bilal-fazlani.blogspot.in/2013/09/adding-log-audit-feature-to-entity.html  references, applies to the current version on nuget package. Is there a specific feature you are waiting for?

**Comment by Bestadd** [comment]
I need mvc5 support

**Comment by bilal-fazlani** [comment]
It's there already. 
You can use TrackerEnabledDbContext for any kind of project. that includes, webforms , mvc, console, winforms , wpf, wcf, etc. 

If you want to use it with asp.net identity 2.0, use TrackerEnabledDbContext.Identity instead.
