### ISSUE TITLE
UserName empty when running on window application

### ISSUE THREAD

**Issue by baoduy** [bilal-fazlani/tracker-enabled-dbcontext#40]
The username of AuditTrail items were empty, How can I contribute the code for this project?

**Comment by bilal-fazlani** [comment]
you can create your own branch and makes changes. I can then merge them to
the main branch.

btw, is the username empty even when u provide it in savechanges(username)
method ?

**Comment by bilal-fazlani** [comment]
closing the issue as there is no response since 3 months.
