### ISSUE TITLE
System.Data.SqlClient.SqlException: Invalid column name 'TableName', while Creating log for saving\adding the entity.

### ISSUE THREAD

**Issue by dreamerNcoder** [bilal-fazlani/tracker-enabled-dbcontext#48]
public static int GetLastAuditLogId(ITrackerContext context, string tableName, object primaryKey)
        {
            string key = primaryKey.ToString();
            return context.AuditLog.Where(x => x.TableName == tableName && x.RecordId == key).OrderByDescending(x => x.AuditLogId).Select(x => x.AuditLogId).FirstOrDefault();
            return 0;
        }

As the AuditLog modal does not contains tableName, hence its giving compilation error.

**Comment by bilal-fazlani** [comment]
This must have been closed by https://github.com/bilal-fazlani/tracker-enabled-dbcontext/commit/5d265fe739eb3e667f42584b96600d99101ea0ca
