### ISSUE TITLE
Please Remove Nuget's Packages From Repository

### ISSUE THREAD

**Issue by rabbal** [bilal-fazlani/tracker-enabled-dbcontext#49]

**Comment by ChocoMachine** [comment]
Why?

**Comment by bilal-fazlani** [comment]
what do you mean ?

**Comment by rabbal** [comment]
for easy download and fork . Or Add 
# NuGet Packages Directory
packages/*
 in .gitignore file for prevent Upload nuget package to repository.
if one person dowload your project then he can restore this packages  in Vs

**Comment by bilal-fazlani** [comment]
Its done
