### ISSUE TITLE
sample project fails to run: Bug on line 61 - in TypeExtension.cs in TrackerEnabledDbContext.Common 

### ISSUE THREAD

**Issue by ChocoMachine** [bilal-fazlani/tracker-enabled-dbcontext#51]
sample project fails to run:

It looks like a cast fails:
 var member = propertyLambda.Body as MemberExpression;

Therefore member is equal to null
Which causes line 63 to execute and throw:
 if (member == null)
                throw new ArgumentException(string.Format(
                    "Expression '{0}' refers to a method, not a property.",
                    propertyLambda));

I am using EF 6.13 , and ASP.NET Identity 2.21

![image](https://cloud.githubusercontent.com/assets/7971514/9651705/58b00afc-5257-11e5-8a7e-975820d80489.png)

**Comment by bilal-fazlani** [comment]
Please paste your POCO model here

**Comment by bilal-fazlani** [comment]
3ee8abfa75f9b9c9f2687b6e0d67a2c5e3fbcafe should fix the issue
