### ISSUE TITLE
Must override IdentityUser Id property with [Key]

### ISSUE THREAD

**Issue by akonyer** [bilal-fazlani/tracker-enabled-dbcontext#6]
If I want to track my ASP.net Identity user class, I cannot do so without overriding the standard Id.

The IdentityUser Id property is not marked as [Key] even though it is the primary key for the entity.

So I have to override the Id property like so:

      [Key]
      public override String Id
      {
         get
         {
            return base.Id;
         }
         set
         {
            base.Id = value;
         }
      }

before I can track changes properly. This should work out of the box without overriding the original Id in my opinion.

**Comment by bilal-fazlani** [comment]
@akonyer I have made a checkin that should fix this issue (among some other issues).
Can you please let me know if it has been resolved ?
Thanks
