### ISSUE TITLE
Is this intended to work with 1:1-relations?

### ISSUE THREAD

**Issue by Equalizer7** [bilal-fazlani/tracker-enabled-dbcontext#67]
Hello.

I am evaluating this tracker and so far it works fine for simple objects. However if I have an object (principal) with a 1:1 relation, I only get audited changes for the principal object - if I change any property of the dependant object no change will show up. Not on creating, not on updating.

Both objects are saved in 1 step of db.SaveChanges().

Before I start to dig deeper and create a small sample for this special case I first wanted to confirm if those kinds of relations are even supported to be tracked.

Best regards,
Michael

**Comment by bilal-fazlani** [comment]
interesting.
could you please show me how your entities look

**Comment by Equalizer7** [comment]
Of course, thanks for your help.

Below I added some shortened versions of Recipe (which is the principal) and RecipeSpecification (dependant) and their corresponding EntityTypeConfigurations. If database is created by EF, the connection looks fine - also the saving works, just not the tracking for the dependant object (RecipeSpecification).

AEntity and ASpecification are some abstract base classes to define some general columns for those entities. They are not known as entities to entity framework and do not exist in the database either.


public class Recipe : AEntity
    {
        [Key]
        public int Id { get; set; }

        public int Version { get; set; }

        public DateTime? ValidFrom { get; set; }

        // One-To-OneOrZero
        public virtual RecipeSpecification RecipeSpecification { get; set; }
    }
public class RecipeETC : EntityTypeConfiguration<Recipe>
    {
        public RecipeETC()
        {
            //this.HasKey(p => p.Id);

            // One-To-OneOrZero
            this.HasOptional(p => p.RecipeSpecification)
                .WithRequired(p => p.Recipe)
                .WillCascadeOnDelete(true);

            // Auditing
            this.TrackAllProperties();
        }
    }



public class RecipeSpecification : ASpecification
    {
        [Key]
        public int Id { get; set; }

        public string RemarksInternal { get; set; }

        // One-To-OneOrZero
        public virtual Recipe Recipe { get; set; }
    }
public class RecipeSpecificationETC : EntityTypeConfiguration<RecipeSpecification>
    {
        public RecipeSpecificationETC()
        {
            //this.HasKey(p => p.Id);

            // Auditing
            this.TrackAllProperties();
        }
    }


On the save click, the following method is called. As it is a disconnected scenario, we use .Find() to get the object and then assign all values from the new object. The values get saved, the tracking for recipe also works, the tracking for RecipeSpecification never shows up.

public Recipe UpdateRecipe(Recipe data)
        {
            using (var context = new GTPOSContext())
            {
                var originalRecipe = context.Recipe.Find(data.Id);
                context.Entry(originalRecipe).CurrentValues.SetValues(data);

                var originalRecipeSpecification = context.RecipeSpecification.Find(data.RecipeSpecification.Id);                context.Entry(originalRecipeSpecification).CurrentValues.SetValues(data.RecipeSpecification);

                context.SaveChanges();
                return data;
            }
        }

**Comment by bilal-fazlani** [comment]
I couldn't really find a solution for this. i tried to reproduce this and saw the same behaviour

**Comment by Equalizer7** [comment]
Thanks for your help.
1:1-relations are quite common in our models, so I guess we have to skip the auditing for now.

**Comment by bilal-fazlani** [comment]
public int Id { get; set; }

    public int Version { get; set; }

    public DateTime? ValidFrom { get; set; }

    public virtual int  RecipeSpecificationId {get;set;}

    // One-To-OneOrZero

    [ForeignKey("RecipeSpecificationId")]
    public virtual RecipeSpecification RecipeSpecification { get; set; }


When you change RecipeSpecification, change in RecipeSpecificationId will
be audited automatically.

You will see the audit log only for Recipe though, not for RecipeSpecification.




On Mon, Nov 9, 2015 at 3:01 PM, Equalizer7 <notifications@github.com> wrote:

> Thanks for your help.
> 1:1-relations are quite common in our models, so I guess we have to skip
> the auditing for now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bilal-fazlani/tracker-enabled-dbcontext/issues/67#issuecomment-155008465>
> .
>



-- 














Thanks & regards

*Bilal Fazlani*

**Comment by Equalizer7** [comment]
My concern is not about changing the RecipeSpecification, but rather changing a field in the RecipeSpecification.

For example, the RemarksInternal field gets updated from "Test" to "Testing". This change will never show up in the auditing tables (at least in my test sample).

Best regards.

**Comment by bilal-fazlani** [comment]
The change you are describing is really common and should work. I tried to reproduce the situation and it seemed to work fine. Can you fork and create a small unit test what has this situation. The unit test should be failing. I can then figure out what is wrong.

**Comment by Equalizer7** [comment]
Sorry for the delay - but I was busy with other projects. A few days off did help though, because I could find the culprit in our code.
Now that I fixed this, it is logging as expected in 1 : 1 - scenarios.

Thanks for your help and patience.

**Comment by bilal-fazlani** [comment]
Ok. cool.
