### ISSUE TITLE
Demo project fails with Invalid object name 'dbo.SplitString'.

### ISSUE THREAD

**Issue by RichardBr** [bilal-fazlani/tracker-enabled-dbcontext#70]
Hi
When I run your demo project it fails with the error message shown below.

I suspect I dont have function on database called 'dbo.SplitString'. When I trying creating one, using samples I found on the internet, it fails with other messages. So can you please explain why Im getting this error.

thanks
Richard

##################################
##################################

Server Error in '/' Application.

Invalid object name 'dbo.SplitString'.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Data.SqlClient.SqlException: Invalid object name 'dbo.SplitString'.

Source Error: 

Line 165:
Line 166:            // Call the original SaveChanges(), which will save both the changes made and the audit records...Note that added entry auditing is still remaining.
Line 167:            int result = await base.SaveChangesAsync(cancellationToken);
Line 168:
Line 169:            //By now., we have got the primary keys of added entries of added entiries because of the call to savechanges.

Source File: M:\Downloads\bilal-fazlani-tracker-enabled-dbcontext-v3.4-0-ge978c94\bilal-fazlani-tracker-enabled-dbcontext-e978c94\TrackerEnabledDbContext.Identity\TrackerIdentityContext.cs    Line: 167

**Comment by bilal-fazlani** [comment]
I will look at it right now. I think it will be best if introduce a smoke
test for this sample project. It keeps crashing every few days. thanks for
this information.

On Fri, Nov 6, 2015 at 2:17 AM, RichardBr <notifications@github.com> wrote:

> Hi
> When I run your demo project it fails with the error message shown below.
>
> I suspect I dont have function on database called 'dbo.SplitString'. When
> I trying creating one, using samples I found on the internet, it fails with
> other messages. So can you please explain why Im getting this error.
>
> thanks
> Richard
>
> ##################################
> Error message starts here
>
> ##################################
>
> Server Error in '/' Application.
>
> Invalid object name 'dbo.SplitString'.
>
> Description: An unhandled exception occurred during the execution of the
> current web request. Please review the stack trace for more information
> about the error and where it originated in the code.
>
> Exception Details: System.Data.SqlClient.SqlException: Invalid object name
> 'dbo.SplitString'.
>
> Source Error:
>
> Line 165:
> Line 166: // Call the original SaveChanges(), which will save both the
> changes made and the audit records...Note that added entry auditing is
> still remaining.
> Line 167: int result = await base.SaveChangesAsync(cancellationToken);
> Line 168:
> Line 169: //By now., we have got the primary keys of added entries of
> added entiries because of the call to savechanges.
>
> Source File:
> M:\Downloads\bilal-fazlani-tracker-enabled-dbcontext-v3.4-0-ge978c94\bilal-fazlani-tracker-enabled-dbcontext-e978c94\TrackerEnabledDbContext.Identity\TrackerIdentityContext.cs
> Line: 167
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bilal-fazlani/tracker-enabled-dbcontext/issues/70>.
>



-- 














Thanks & regards

*Bilal Fazlani*

**Comment by bilal-fazlani** [comment]
@RichardBr , When does it fail exactly ? I am trying to reproduce this error

**Comment by RichardBr** [comment]
I have run your demo again on a new database and everything now appears to be fine. But when I go back to the original database I continue to see the error. The error happens when I try to create a blog record. I going to now accept some error occured during the creation of the database !
