### ISSUE TITLE
TrackerContext cannot be mocked with Moq framework

### ISSUE THREAD

**Issue by johnmannix** [bilal-fazlani/tracker-enabled-dbcontext#71]
When trying to mock a type derived from TrackerContext with the Moq framework there is an issue which prevents the mock from being instantiated. The issue is described in this bug report for Moq:

https://github.com/castleproject/Core/issues/106

Whilst it appears this is an issue with Moq, it can be worked around by ensuring that type names of generic types match between the interface and the class.

**Comment by johnmannix** [comment]
Pull request for work around https://github.com/bilal-fazlani/tracker-enabled-dbcontext/pull/72

**Comment by bilal-fazlani** [comment]
@johnmannix I can't pull your code because you renamed TEntity with TTable. But The correct TypeParam is TEntity. So I renamed everything else to TEntity. Since they are all consistent now, the mocking should work.

Let me know. Thanks.

**Comment by johnmannix** [comment]
@bilal-fazlani Thanks. Would you be able to update the nuget package with this fix?

**Comment by bilal-fazlani** [comment]
Yes Will do by tomorrow afternoon

On Mon, Nov 9, 2015 at 3:14 PM, John Mannix <notifications@github.com>
wrote:

> @bilal-fazlani <https://github.com/bilal-fazlani> Thanks. Would you be
> able to update the nuget package with this fix?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bilal-fazlani/tracker-enabled-dbcontext/issues/71#issuecomment-155012313>
> .
>



-- 














Thanks & regards

*Bilal Fazlani*

**Comment by bilal-fazlani** [comment]
Done - 
https://www.nuget.org/packages/TrackerEnabledDbContext/3.4.5

**Comment by johnmannix** [comment]
Thanks @bilal-fazlani that solves my problem
