### ISSUE TITLE
trackerenableddbcontext in code first from database

### ISSUE THREAD

**Issue by uikro** [bilal-fazlani/tracker-enabled-dbcontext#74]
How do I use trackerenableddbcontext in code first from database?

**Comment by bilal-fazlani** [comment]
Have you gone through the wiki ?
https://github.com/bilal-fazlani/tracker-enabled-dbcontext/wiki

**Comment by bilal-fazlani** [comment]
I am sorry but I feel this question is really broad. Please go through the wiki and let me know if there is something specific I can help you with. Thank you.
