### ISSUE TITLE
Update to version 3.5 dll issues

### ISSUE THREAD

**Issue by banban** [bilal-fazlani/tracker-enabled-dbcontext#75]
Ufter update to 3.5 by Nuget, I can see both dlls have the same version 3.5 but when I deploy it to server I can see error caused by dll dependencies:
Could not load file or assembly 'TrackerEnabledDbContext.Common, Version=3.4.5.0, Culture=neutral, PublicKeyToken=4f92af0b908c4a0a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference

It looks like TrackerEnabledDbContext has ref to TrackerEnabledDbContext.Common 3.4.5
I have double checked deployed files versions. Both of them 3.5
There is no dlls in GAC, just in working folder.

I have reinstalled TrackerEnabledDbContext packages, deleted all data from destination folder and redeployed to server again. Now it works. Was is local cache issue?

**Comment by bilal-fazlani** [comment]
Yes. It was. I verified now and its working fine.
