### ISSUE TITLE
SqlServerCE

### ISSUE THREAD

**Issue by maurosampietro** [bilal-fazlani/tracker-enabled-dbcontext#76]
Hi, it is not possible to use the tool with System.Data.SqlServerCe as provider.
Basically because DateTimeOffset is not supported. The error is:
"There is no store type corresponding to the EDM type 'Edm.DateTimeOffset(Nullable=False)' of primitive type 'DateTimeOffset'".

Here a workaround:
http://stackoverflow.com/questions/5725439/ef-4-1-code-first-sqlce-and-datetimeoffset

**Comment by pirimoglu** [comment]
Same issue is needed for **SQLite** databases. SQLite is not supported DateTimeOffset data type.

Given error:
>There is no store type corresponding to the EDM type 'Edm.DateTimeOffset' of primitive type 'DateTimeOffset'.

**Comment by bilal-fazlani** [comment]
https://www.nuget.org/packages/TrackerEnabledDbContext/3.5.1

**Comment by maurosampietro** [comment]
It seems to work now. Thank you!

**Comment by JkumarTech** [comment]
I have same problem with 3.5.2 with OData v 4.0
