### ISSUE TITLE
Support MySQL provider

### ISSUE THREAD

**Issue by berniezhao** [bilal-fazlani/tracker-enabled-dbcontext#79]
I use Entity Framework with MySQL and it has been transparent to the application.
Seems like the models use `DateTimeOffset` which is only available in SQL server.

**Comment by StuartFerguson** [comment]
Is there any timescale on this update being done as I was just about to investigate the usage of this pacakage with my Identity solution but this uses MySQL.  Is the only update to make the property in the Model a DateTime type and not DateTime offset ?

**Comment by pirimoglu** [comment]
Same issue is needed for **SQLite** databases. SQLite is not supported DateTimeOffset data type.

Given error:
>There is no store type corresponding to the EDM type 'Edm.DateTimeOffset' of primitive type 'DateTimeOffset'.

**Comment by maurosampietro** [comment]
this issue is related to #76

**Comment by buraksarica** [comment]
When will this change take place in a release on nuget?

**Comment by bilal-fazlani** [comment]
https://www.nuget.org/packages/TrackerEnabledDbContext/3.5.1
Can someone please let me know if this new version solved the issue
