### ISSUE TITLE
Add the entity being logged to the AuditLogGeneratedEventArgs

### ISSUE THREAD

**Issue by AlexanderLindsay** [bilal-fazlani/tracker-enabled-dbcontext#83]
It might be helpful to add the entity being logged to the `AuditLogGeneratedEventArgs`.

```c#
public class AuditLogGeneratedEventArgs : System.EventArgs
{
    public AuditLogGeneratedEventArgs(AuditLog log, object entity)
    {
        Log = log;
        Entity = entity;
    }

    public AuditLog Log { get; internal set; }

    public object Entity { get; internal set; }

    public bool SkipSaving { get; set; } = false;
 }
```

This change would allow the user to modify the entity itself it necessary when subscribing to the event. Which could be useful in setting a `LastUpdatedDate` or `LastUpdateBy` column. 

I have the change (and modified tests) in a fork.

**Comment by bilal-fazlani** [comment]
Good Idea.

Add a unit test around it. Create a pull request. I will merge it and
release it on nuget.

**Comment by bilal-fazlani** [comment]
I have released it on nuget. I have one question though.
**What happens when user says SkipSaving = true; ?**
I would ideally want in that case that the log should not get saved but the changes to entity should be saved.

And now since this event can be used to save the entity and the log, the property name "skipsaving" should be specific such as "skipsavinglog"

**Comment by bilal-fazlani** [comment]
https://www.nuget.org/packages/TrackerEnabledDbContext/

**Comment by AlexanderLindsay** [comment]
The changes to the entity should still be saved when skipsaving is set to true. I should have added a test case for that.

I also agree that skipsavinglogs is a more accurate name for that property. I would worry about changing that, however, as it would be a breaking change. Though a small one.
