### ISSUE TITLE
How does this get library work with Microsoft.AspNet.Identity.UserManager?

### ISSUE THREAD

**Issue by patrickmichalina** [bilal-fazlani/tracker-enabled-dbcontext#87]
This nifty manager that is provided abstracts away the SaveChanges method. What does it look like to use the UserManager with your library? If the Current.User is in the OwinContext will it automatically persist that username?

**Comment by bilal-fazlani** [comment]
>What does it look like to use the UserManager with your library?

I dint really understand question.

>If the Current.User is in the OwinContext will it automatically persist that username?

You will have to pass the username to savechanges() method. It won't automatically persist it

**Comment by patrickmichalina** [comment]
An example:

```
public class UsersController
{
    private ApplicationUserManager _AppUserManager = null;

    protected ApplicationUserManager AppUserManager
    {
        get
        {
            return _AppUserManager ?? Request.GetOwinContext().GetUserManager<ApplicationUserManager>();
        }
    }

    public async Task<IHttpActionResult> CreateUser(ApplicationUser userModel)
    {
        if (!ModelState.IsValid) return BadRequest(ModelState);

        var user = new ApplicationUser()
        {
            UserName = userModel.Username,
            Email = userModel.Email,
            FirstName = userModel.FirstName,
            LastName = userModel.LastName,
            JoinDate = DateTime.Now.Date,
        };

        // HERE is where ASP.NET Identity is persisting the new user to the database.
        // in the UserManager there is a Store, which has a DbContext. Of course - it doesnt have a context.SaveChanges(string username)
        // I was wondering if your identity library injected the user name there
        var addUserResult = await this.AppUserManager.CreateAsync(user, userModel.Password);

        Uri locationHeader = new Uri(Url.Link("Api", new { id = user.Id }));

        return Created(locationHeader, TheModelFactory.Create(user));
    }
}
```

**Comment by patrickmichalina** [comment]
https://msdn.microsoft.com/en-us/magazine/dn605872.aspx

**Comment by patrickmichalina** [comment]
Another way to say it: I want to audit the UserManager itself. Phone number changes or similar.

**Comment by bilal-fazlani** [comment]
This feature doesn't exist yet. But it's a good idea. I am tempted to implement this feature but I can't give you a date when I will implement this.

**Comment by bilal-fazlani** [comment]
https://github.com/bilal-fazlani/tracker-enabled-dbcontext/commit/de82edab6617ad5c922a8186b0abea7c4da887bb

I am currently able to track the changes on application users when crud operations are performed on application users using dbcontext... not with Microsoft.AspNet.Identity.UserManager.

can you send me a small hello world application with the functionality you want. I will try to integrate with Microsoft.AspNet.Identity.UserManager.

**Comment by bilal-fazlani** [comment]
Okay I was able to make it work.

Just use this code

```c#
public class UsersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private UserManager<ApplicationUser> _userManager;

        public UsersController()
        {
            db.ConfigureUsername(() => User?.Identity?.Name);
            _userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
        }

//you code here
}
```

**Comment by patrickmichalina** [comment]
db.ConfigureUsername is a method on TrackerDbContext? If so, awesome and I will try it later today!

**Comment by bilal-fazlani** [comment]
> db.ConfigureUsername is a method on TrackerDbContext?

yes.
