### ISSUE TITLE
Empty AuditLog

### ISSUE THREAD

**Issue by bilal-fazlani** [bilal-fazlani/tracker-enabled-dbcontext#9]
when I call the SaveChanges(userid) method and my entity don't have any data changes, for example a user go the the edit option, and click on save without changing anything, the AuditLog get the operation information but the AuditLogDetails dont have any, of course, the user didn´t change anything, Its there a way to ignore this operations when no data was changed, i mean to ignore the audit on AuditLog table﻿

**Comment by demispb** [comment]
Thanks for creating this issue from my comment on your blog, please keep me updated, Regards DemisPB

**Comment by bilal-fazlani** [comment]
hi @demispb ,
i was trying to reproduce this defect and I couldn't. could you please share your code that that causes this behaviour ?

**Comment by bilal-fazlani** [comment]
closing issue
