### ISSUE TITLE
event add/remove mismatch for coreTracker.OnAuditLogGenerated

### ISSUE THREAD

**Issue by mikhail-barg** [bilal-fazlani/tracker-enabled-dbcontext#95]
I've noticed the following code lines:

```C#
public class TrackerContext : DbContext, ITrackerContext
{
...
        private void InitializeCoreTracker()
        {
            _coreTracker = new CoreTracker(this);
            _coreTracker.OnAuditLogGenerated += RaiseOnAuditLogGenerated;
        }
...
        private void ReleaseEventHandlers()
        {
            _coreTracker.OnAuditLogGenerated -= OnAuditLogGenerated;
        }
```

and same lines in `TrackerIdentityContext`. Note that event handler being registered is `RaiseOnAuditLogGenerated` while in unregister it's `OnAuditLogGenerated`. This looks like a bug.

**Comment by bilal-fazlani** [comment]
Definitely looks a like a big.
Do you want to create a pull request or u want to me to fix. I you can
create a PR that would be great

**Comment by mikhail-barg** [comment]
Yes, I'll make a PR, but I don't think I'm able to run tests to check if everything is OK. The tests look like requiring SQLExpress or LocalDB, which I currently don't have. Could you check tests yourself, or is it quick to setup test environment?

**Comment by bilal-fazlani** [comment]
Ci is setup. Tests will run automatically when u push changes

**Comment by mikhail-barg** [comment]
Got it. Here's the PR: #95
Caused a bit of refactoring too.
